---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "helm-openresty.fullname" . }}-cm
data:
  index.html: |
    <html>
    <head>
        <title>Тестовая страница openresty</title>
        <meta charset="UTF-8">
    </head>
    <body>
      <h1>Тестовая страница openresty</h1>
    </body>
    </html>
