application:
  reloader: false
  replicaCount: 1
  revisionHistoryLimit: 3
  podAnnotations: {}
  imagePullSecrets: []
  image:
    repository: openresty/openresty
    tag: "1.19.9.1-4-centos-rpm"
    pullPolicy: IfNotPresent
  probe:
    readinessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
  resources:
    limits:
      cpu: "0.2"
      memory: "400Mi"
    requests:
      cpu: "0.1"
      memory: "200Mi"

service:
  type: ClusterIP
  #type: NodePort
  #nodePort: 31002
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  className: "system-ingress"
  annotations:
    certmanager.k8s.io/cluster-issuer: monitoring-issuer
  hosts:
    - host: openresty.dot.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - openresty
      secretName: openresty-tls
